name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        verTag: ['1.4']
    steps:
    - uses: actions/checkout@v1
    - name: Create docker tag
      id: create_docker_tag
      run: |
        TAG=aauevt/ci-go-base:${{ matrix.verTag }}
        echo ::set-output name=TAG::$TAG
    - name: Build docker image
      run: |
        docker build . \
            --no-cache \
            -t "${{ steps.create_docker_tag.outputs.TAG }}" \
            --build-arg BASE_IMAGE_TAG=${{ matrix.verTag }}
    - name: Push image to DockerHub
      if: github.event_name != 'pull_request'
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u aauevt --password-stdin
        docker push ${{ steps.create_docker_tag.outputs.TAG }}
