name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        verTag: ['1.7']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Create docker tag
        id: create_docker_tag
        run: |
          TAG=aauevt/ci-go-base:${{ matrix.verTag }}
          echo ::set-output name=TAG::$TAG
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: aauevt
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          no-cache: true
          tags: ${{ steps.create_docker_tag.outputs.TAG }}
          build-args: "BASE_IMAGE_TAG=${{ matrix.verTag }}"
